version: '3.3'
services:
  api:
    build: .
    restart: always
    image: tomcat
    container_name: tomcat
    # volumes:
    #   - ./api/index.html:/usr/local/tomcat/webapps/test/index.html
    ports:
      - 8080:8080
    environment:
      TZ: America/New_York
  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'dbEcomerce'
      MYSQL_USER: 'usr_grp1'
      MYSQL_PASSWORD: 'pwd2022@'
      MYSQL_ROOT_PASSWORD: 'pwdrt2022@'
      TZ: America/New_York
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqldb-data:/var/lib/mysql

volumes:
  myapi:
  mysqldb-data: {}
      # external: true

